import React, { useState, useEffect } from 'react';
import { api } from '../../services/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './FinancialReports.css';

const FinancialReports = () => {
  const [range, setRange] = useState('monthly');
  const [selectedDate, setSelectedDate] = useState(() => {
    const today = new Date();
    return today.toISOString().split('T')[0]; // yyyy-MM-dd
  });
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [timelinePage, setTimelinePage] = useState(1);

  useEffect(() => {
    setTimelinePage(1);
  }, [range, selectedDate]);

  useEffect(() => {
    fetchReport();
  }, [range, selectedDate]);

  const fetchReport = async () => {
    setLoading(true);
    setError(null);
    try {
      // Map monthly or weekly selection to yyyy-MM-dd for C# parsing
      let dateParam = selectedDate;
      if (range === 'yearly') {
        dateParam = `${selectedDate.split('-')[0]}-01-01`;
      }
      const data = await api.getFinancialReport(range, dateParam);
      setReportData(data);
    } catch (err) {
      console.error('Failed to load financial reports', err);
      setError(err.message || 'Failed to fetch financial report');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'NPR' // Aligning with Nepalese Rupees matching other pages' currency
    }).format(val || 0);
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const handleRangeChange = (newRange) => {
    setRange(newRange);
    const today = new Date();
    if (newRange === 'yearly') {
      setSelectedDate(`${today.getFullYear()}-01-01`);
    } else {
      setSelectedDate(today.toISOString().split('T')[0]);
    }
  };

  // Corporate Styled jsPDF Export Statement
  const handleExportPDF = () => {
    if (!reportData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Elegant Header Decorator ---
    doc.setFillColor(33, 37, 41); // Slate Dark Theme
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text("6IX7EVEN AUTO PARTS", 14, 18);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text("CORPORATE FINANCIAL STATEMENT", 14, 30);

    // Metadata Right-aligned
    const runUser = api.getUser()?.fullName || 'Administrator';
    doc.setFontSize(9);
    doc.text(`STATEMENT RANGE: ${range.toUpperCase()}`, pageWidth - 80, 16);
    doc.text(`GENERATED BY: ${runUser}`, pageWidth - 80, 23);
    doc.text(`DATE GENERATED: ${new Date().toLocaleDateString()}`, pageWidth - 80, 30);

    // Reset styles
    doc.setTextColor(33, 37, 41);
    
    // --- 1. Summary Block ---
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text("1. Executive Summary Table", 14, 52);

    const summaryRows = [
      ["Parameter", "Statement Aggregations"],
      ["Reporting Start Date", formatDate(reportData.startDate)],
      ["Reporting End Date", formatDate(reportData.endDate)],
      ["Gross Sales Revenue", formatCurrency(reportData.totalRevenue)],
      ["Operating Cost/Expenses", formatCurrency(reportData.totalExpenses)],
      ["Net Trading Profit", formatCurrency(reportData.netProfit)],
      ["Sales Invoices Settled", reportData.totalOrders.toString()],
      ["Vendor Bills Incurred", reportData.totalPurchaseInvoices.toString()],
      ["Average Invoice Basket Value", formatCurrency(reportData.averageOrderValue)]
    ];

    autoTable(doc, {
      startY: 57,
      head: [summaryRows[0]],
      body: summaryRows.slice(1),
      theme: 'grid',
      headStyles: { fillColor: [224, 79, 95], textColor: [255, 255, 255] }, // Sleek red theme
      columnStyles: {
        0: { fontStyle: 'bold', width: 90 },
        1: { halign: 'right' }
      }
    });

    let lastY = doc.lastAutoTable.finalY + 15;

    // --- 2. Periodic Timeline Breakdown ---
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text("2. Periodic Sales & Operating Costs", 14, lastY);

    const breakdownHeaders = [["Timeline Period", "Gross Revenue", "Operating Expenses", "Net Income"]];
    const breakdownBody = reportData.periodicBreakdown.map(item => [
      item.periodLabel,
      formatCurrency(item.revenue),
      formatCurrency(item.expenses),
      formatCurrency(item.revenue - item.expenses)
    ]);

    autoTable(doc, {
      startY: lastY + 5,
      head: breakdownHeaders,
      body: breakdownBody,
      theme: 'striped',
      headStyles: { fillColor: [54, 69, 79], textColor: [255, 255, 255] }
    });

    // Page Break if needed
    doc.addPage();

    // --- 3. Top Performers and Expenses Breakdown ---
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text("3. Top Volume Sales Breakdown", 14, 20);

    const productsHeaders = [["Rank", "Part Catalog Description", "Units Distributed", "Revenue Earned"]];
    const productsBody = reportData.topSellingProducts.map((p, index) => [
      `#${index + 1}`,
      p.partName,
      p.quantitySold.toString(),
      formatCurrency(p.totalRevenue)
    ]);

    autoTable(doc, {
      startY: 25,
      head: productsHeaders,
      body: productsBody,
      theme: 'grid',
      headStyles: { fillColor: [33, 150, 243] }
    });

    lastY = doc.lastAutoTable.finalY + 15;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text("4. Major Operating Costs / Stock Spending", 14, lastY);

    const expenseHeaders = [["Rank", "Vendor Acquired Component", "Units Purchased", "Total Acquisitions Spending"]];
    const expenseBody = reportData.topExpenses.map((e, index) => [
      `#${index + 1}`,
      e.partName,
      e.quantityPurchased.toString(),
      formatCurrency(e.totalCost)
    ]);

    autoTable(doc, {
      startY: lastY + 5,
      head: expenseHeaders,
      body: expenseBody,
      theme: 'grid',
      headStyles: { fillColor: [156, 39, 176] }
    });

    // Professional Footer Signatures
    lastY = doc.lastAutoTable.finalY + 30;
    if (lastY > doc.internal.pageSize.height - 40) {
      doc.addPage();
      lastY = 30;
    }

    doc.setDrawColor(200, 200, 200);
    doc.line(14, lastY, 74, lastY);
    doc.line(pageWidth - 74, lastY, pageWidth - 14, lastY);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text("Executive Approver Signature", 14, lastY + 5);
    doc.text("Authorized Audit Signature", pageWidth - 74, lastY + 5);

    // Save File
    const fileSuffix = range.toUpperCase() + "_" + selectedDate;
    doc.save(`Financial_Statement_${fileSuffix}.pdf`);
  };

  const renderDateSelector = () => {
    if (range === 'yearly') {
      const currentYear = new Date().getFullYear();
      const years = Array.from({ length: 5 }, (_, i) => currentYear - i);
      return (
        <select 
          value={selectedDate.split('-')[0]} 
          onChange={(e) => setSelectedDate(`${e.target.value}-01-01`)}
          className="report-date-input"
        >
          {years.map(y => (
            <option key={y} value={y}>{y} Fiscal Year</option>
          ))}
        </select>
      );
    }

    if (range === 'weekly' || range === 'monthly') {
      return (
        <input 
          type="month"
          value={selectedDate.substring(0, 7)}
          onChange={(e) => setSelectedDate(`${e.target.value}-01`)}
          className="report-date-input"
        />
      );
    }

    return (
      <input 
        type="date"
        value={selectedDate}
        onChange={(e) => setSelectedDate(e.target.value)}
        className="report-date-input"
      />
    );
  };

  return (
    <div className="financial-reports-container">
      <div className="reports-top-controls">
        <div className="header-info">
          <h2>Financial Statements & Analytics</h2>
          <p className="subtitle">Audit revenue, operations costs, and net trading margins dynamically.</p>
        </div>
        
        <div className="controls-row">
          <div className="range-filter-tabs">
            {['daily', 'weekly', 'monthly', 'yearly'].map((r) => (
              <button
                key={r}
                className={`tab-btn ${range === r ? 'active' : ''}`}
                onClick={() => handleRangeChange(r)}
              >
                {r.toUpperCase()}
              </button>
            ))}
          </div>

          <div className="date-picker-wrap">
            {renderDateSelector()}
            <button 
              onClick={handleExportPDF} 
              className="btn-export-pdf" 
              disabled={loading || error || !reportData}
            >
              <svg className="btn-icon-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ width: '14px', height: '14px' }}><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
              Export Statement
            </button>
          </div>
        </div>
      </div>

      {loading ? (
        <div className="report-loading-container">
          <div className="loading-spinner"></div>
          <p>Auditing transaction ledgers...</p>
        </div>
      ) : error ? (
        <div className="report-error-container">
          <p className="error-message">⚠️ Error: {error}</p>
          <button className="admin-btn-outline" onClick={fetchReport}>Retry Query</button>
        </div>
      ) : (
        <>
          {/* KPI Dashboard Cards */}
          <div className="kpi-dashboard-grid">
            <div className="kpi-card revenue-card">
              <div className="kpi-header">
                <span>Gross Trading Revenue</span>
                <svg className="kpi-icon positive" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M23 6l-9.5 9.5-5-5L1 18m22-12h-6m6 0v6"/></svg>
              </div>
              <h3 className="kpi-value">{formatCurrency(reportData.totalRevenue)}</h3>
              <p className="kpi-subtext">All billing orders completed</p>
            </div>

            <div className="kpi-card expenses-card">
              <div className="kpi-header">
                <span>Operational Costs</span>
                <svg className="kpi-icon negative" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M23 18l-9.5-9.5-5 5L1 6m22 12h-6m6 0v-6"/></svg>
              </div>
              <h3 className="kpi-value">{formatCurrency(reportData.totalExpenses)}</h3>
              <p className="kpi-subtext">Stock acquisitions & invoices</p>
            </div>

            <div className="kpi-card profit-card">
              <div className="kpi-header">
                <span>Net Trading Profit</span>
                <div className={`profit-indicator ${reportData.netProfit >= 0 ? 'gain' : 'loss'}`}>
                  {reportData.netProfit >= 0 ? 'PROFIT' : 'LOSS'}
                </div>
              </div>
              <h3 className={`kpi-value ${reportData.netProfit >= 0 ? 'gain-text' : 'loss-text'}`}>
                {formatCurrency(reportData.netProfit)}
              </h3>
              <p className="kpi-subtext">Operating trading margin</p>
            </div>

            <div className="kpi-card volume-card">
              <div className="kpi-header">
                <span>Sales vs Vendor Invoices</span>
                <svg className="kpi-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/></svg>
              </div>
              <h3 className="kpi-value">{reportData.totalOrders} <span className="vol-separator">/</span> {reportData.totalPurchaseInvoices}</h3>
              <p className="kpi-subtext">Order count vs Vendor bills</p>
            </div>

            <div className="kpi-card basket-card">
              <div className="kpi-header">
                <span>Average Order Value</span>
                <svg className="kpi-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 1v22m5-18H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>
              </div>
              <h3 className="kpi-value">{formatCurrency(reportData.averageOrderValue)}</h3>
              <p className="kpi-subtext">Average basket settlement</p>
            </div>
          </div>

          {/* Analytical Tables Grid */}
          <div className="analytical-reports-grid">
            
            {/* Timeline Breakdown Table */}
            <div className="analytical-card full-span-card">
              <div className="card-header timeline-card-header">
                <div>
                  <h3>1. Comparative Periodic Sales & Operating Costs</h3>
                  <p>Timeline summary breakdown for {formatDate(reportData.startDate)} to {formatDate(reportData.endDate)}</p>
                </div>
                {(() => {
                  const itemsPerPage = 15;
                  const rawTimeline = reportData?.periodicBreakdown || [];
                  const totalItems = rawTimeline.length;
                  const totalPages = Math.ceil(totalItems / itemsPerPage) || 1;
                  const startIndex = (timelinePage - 1) * itemsPerPage;
                  const endIndex = Math.min(startIndex + itemsPerPage, totalItems);
                  
                  if (totalPages <= 1) return null;

                  return (
                    <div className="timeline-pagination-controls">
                      <button 
                        type="button"
                        className="pagination-arrow-btn"
                        disabled={timelinePage === 1}
                        onClick={() => setTimelinePage(prev => Math.max(prev - 1, 1))}
                      >
                        ◀ Prev 15
                      </button>
                      <span className="pagination-info">
                        Showing {startIndex + 1}-{endIndex} of {totalItems} (Page {timelinePage}/{totalPages})
                      </span>
                      <button 
                        type="button"
                        className="pagination-arrow-btn"
                        disabled={timelinePage === totalPages}
                        onClick={() => setTimelinePage(prev => Math.min(prev + 1, totalPages))}
                      >
                        Next 15 ▶
                      </button>
                    </div>
                  );
                })()}
              </div>
              <div className="table-wrapper">
                <table className="analytical-table">
                  <thead>
                    <tr>
                      <th>Timeline Period</th>
                      <th>Gross Revenue</th>
                      <th>Operating Expenses</th>
                      <th>Net Profit/Margin</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(() => {
                      const itemsPerPage = 15;
                      const rawTimeline = reportData?.periodicBreakdown || [];
                      const startIndex = (timelinePage - 1) * itemsPerPage;
                      const paginatedBreakdown = rawTimeline.slice(startIndex, startIndex + itemsPerPage);

                      if (paginatedBreakdown.length === 0) {
                        return (
                          <tr>
                            <td colSpan="4" className="empty-row">No transactional records registered in this window.</td>
                          </tr>
                        );
                      }

                      return paginatedBreakdown.map((item, index) => (
                        <tr key={index}>
                          <td className="period-label">{item.periodLabel}</td>
                          <td className="gain-text font-bold">{formatCurrency(item.revenue)}</td>
                          <td className="loss-text font-bold">{formatCurrency(item.expenses)}</td>
                          <td className={`font-bold ${item.revenue - item.expenses >= 0 ? 'gain-text' : 'loss-text'}`}>
                            {formatCurrency(item.revenue - item.expenses)}
                          </td>
                        </tr>
                      ));
                    })()}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Top Products */}
            <div className="analytical-card">
              <div className="card-header">
                <h3>2. Top-Selling Catalog Products</h3>
                <p>Products generating the highest revenue within the period</p>
              </div>
              <div className="table-wrapper">
                <table className="analytical-table">
                  <thead>
                    <tr>
                      <th>Rank</th>
                      <th>Part Description</th>
                      <th>Qty Sold</th>
                      <th>Revenue</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.topSellingProducts.length === 0 ? (
                      <tr>
                        <td colSpan="4" className="empty-row">No products sold in this period.</td>
                      </tr>
                    ) : (
                      reportData.topSellingProducts.map((prod, index) => (
                        <tr key={index}>
                          <td className="rank-cell">#{index + 1}</td>
                          <td className="part-desc">{prod.partName}</td>
                          <td className="font-bold">{prod.quantitySold}</td>
                          <td className="gain-text font-bold">{formatCurrency(prod.totalRevenue)}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Top Expenses */}
            <div className="analytical-card">
              <div className="card-header">
                <h3>3. Major Stock Expenditures</h3>
                <p>Acquisition spending on vendor parts restock</p>
              </div>
              <div className="table-wrapper">
                <table className="analytical-table">
                  <thead>
                    <tr>
                      <th>Rank</th>
                      <th>Component restocked</th>
                      <th>Qty Bought</th>
                      <th>Acquisitions Spending</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.topExpenses.length === 0 ? (
                      <tr>
                        <td colSpan="4" className="empty-row">No vendor restocks registered in this period.</td>
                      </tr>
                    ) : (
                      reportData.topExpenses.map((exp, index) => (
                        <tr key={index}>
                          <td className="rank-cell">#{index + 1}</td>
                          <td className="part-desc">{exp.partName}</td>
                          <td className="font-bold">{exp.quantityPurchased}</td>
                          <td className="loss-text font-bold">{formatCurrency(exp.totalCost)}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

          </div>
        </>
      )}
    </div>
  );
};

export default FinancialReports;
